name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send Discord Notification
        if: success()
        env:
          DISCORD_WEBHOOK: ${{ secrets.RELEASES_WEBHOOK }}
          TAG_NAME: ${{ github.ref_name }}
          RELEASE_URL: https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{
              \"embeds\": [{
                \"title\": \"New Release: $TAG_NAME\",
                \"description\": \"A new version of iteratr has been released!\",
                \"color\": 5814783,
                \"fields\": [
                  {
                    \"name\": \"Version\",
                    \"value\": \"$TAG_NAME\",
                    \"inline\": true
                  },
                  {
                    \"name\": \"Repository\",
                    \"value\": \"[iteratr](https://github.com/${{ github.repository }})\",
                    \"inline\": true
                  }
                ],
                \"footer\": {
                  \"text\": \"Released via GitHub Actions\"
                },
                \"timestamp\": \"$(date -u +%Y-%m-%dT%H:%M:%S.000Z)\",
                \"url\": \"$RELEASE_URL\"
              }]
            }" \
            $DISCORD_WEBHOOK
